// Generated by npm run build:ui from shared popup, styles and SVG sources.
// Checked in so extension/ loads directly; regenerate after editing its source assets.
globalThis.BiliSkipPlayerAssets = Object.freeze({
  html: `<main aria-label="BiliSkip 广告跳过">
      <header>
        <span class="brand-icon"><svg
  xmlns="http://www.w3.org/2000/svg"
  width="256"
  height="256"
  viewBox="0 0 256 256"
  fill="none"
  role="img"
  aria-labelledby="biliskip-icon-title biliskip-icon-description"
>
  <title id="biliskip-icon-title">BiliSkip</title>
  <desc id="biliskip-icon-description">
    蓝色双天线电视，屏幕内有白色播放键，右下角为带蓝色禁止标记的金色硬币。
  </desc>
  <!--
    TV silhouette adapted from Lucide / Feather tv; composition and colors by BiliSkip.
    Source: https://github.com/lucide-icons/lucide/blob/main/icons/tv.svg

    ISC License
    Copyright (c) 2026 Lucide Icons and Contributors

    Permission to use, copy, modify, and/or distribute this software for any
    purpose with or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

    The MIT License (MIT)
    Copyright (c) 2013-present Cole Bemis
    Copyright (c) 2026 bakapiano (BiliSkip composition and modifications)

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
  -->
  <defs>
    <mask
      id="biliskip-tv-cutout"
      x="0"
      y="0"
      width="256"
      height="256"
      maskUnits="userSpaceOnUse"
      maskContentUnits="userSpaceOnUse"
      style="mask-type: luminance"
    >
      <rect width="256" height="256" fill="#fff" />
      <circle cx="195" cy="197" r="62" fill="#000" />
    </mask>
  </defs>
  <g id="television" mask="url(#biliskip-tv-cutout)">
    <path
      d="M78 28L122 68L165 28"
      stroke="#079ed1"
      stroke-width="13"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
    <path
      d="M66 215L59 231M177 215L184 231"
      stroke="#079ed1"
      stroke-width="12"
      stroke-linecap="round"
    />
    <rect x="19" y="66" width="208" height="155" rx="28" fill="#079ed1" />
    <rect
      x="35"
      y="82"
      width="176"
      height="123"
      rx="17"
      stroke="#92ddf3"
      stroke-width="5"
    />
    <path
      d="M94 109L150 143L94 177V109Z"
      fill="#fff"
      stroke="#fff"
      stroke-width="4"
      stroke-linejoin="round"
    />
  </g>
  <g id="coin">
    <circle cx="195" cy="197" r="43" fill="#f6a817" />
    <circle cx="195" cy="197" r="34" stroke="#ffcf68" stroke-width="3.5" />
    <path
      d="M206 180C202 176 187 175 185 184C182 197 207 192 206 205C205 216 188 217 182 211M195 171V222"
      stroke="#fff"
      stroke-width="5.5"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
  </g>
  <g id="block" stroke="#079ed1" stroke-linecap="round">
    <circle cx="195" cy="197" r="52" stroke-width="9" />
    <path d="M224 155L166 239" stroke-width="11" />
  </g>
</svg>
</span>
        <h1>BiliSkip</h1>
        <span id="source">本地优先</span>
        <button id="options" type="button">设置</button>
      </header>
      <p id="video-title">当前视频</p>
      <p id="status" role="status" aria-live="polite">正在连接视频页…</p>
      <div class="actions">
        <button id="analyze" class="primary" type="button" disabled>分析当前视频</button>
        <button id="refresh" type="button" disabled>读取缓存</button>
        <button id="online" type="button" disabled>读取线上缓存</button>

        <button id="skip" type="button" disabled>跳过当前广告</button>
        <button id="undo" type="button" disabled>撤销跳过</button>
      </div>
      <button
        id="toggle"
        class="skip-switch"
        role="switch"
        aria-checked="false"
        type="button"
        disabled
      >
        自动跳过广告
      </button>
      <div id="meter" aria-label="广告时间轴"></div>
      <details open>
        <summary id="summary">广告标记</summary>
        <div id="segments"></div>
      </details>
      <p id="meta" class="hint"></p>
      <button id="upload" type="button" hidden>上传到线上缓存</button>
      <p id="upload-status" class="hint"></p>
      <footer>金色区间为符合跳过条件的广告。关闭面板后继续处理。</footer>
    </main>`,
  css: `:root {
  color-scheme: light;
  font:
    13px/1.55 system-ui,
    sans-serif;
  color: #253b51;
  background: #f7fafc;
}
* {
  box-sizing: border-box;
}
body {
  width: 380px;
  margin: 0;
}
main {
  padding: 14px;
  max-height: 600px;
  overflow: auto;
}
header {
  display: flex;
  align-items: center;
  gap: 10px;
  border-bottom: 1px solid #e1eaf2;
  padding-bottom: 10px;
}
h1 {
  font-size: 18px;
  color: #167ba3;
  margin: 0;
}
#source {
  margin-left: auto;
  font-size: 11px;
  color: #6e8092;
}
#video-title {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  color: #62758a;
  font-size: 12px;
  margin: 10px 0 6px;
}
#status {
  white-space: pre-wrap;
  min-height: 20px;
  margin: 6px 0 12px;
}
.error {
  color: #b54249;
}
.actions {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}
button {
  font: inherit;
  color: #35536e;
  background: #fff;
  border: 1px solid #ccdde9;
  border-radius: 7px;
  padding: 5px 9px;
  cursor: pointer;
}
button:hover {
  background: #eef6fc;
}
button:disabled {
  opacity: 0.45;
  cursor: default;
}
.primary {
  background: #087faf;
  border-color: #087faf;
}
button:focus-visible,
summary:focus-visible {
  outline: 2px solid #079ed166;
  outline-offset: 2px;
}
#meter {
  height: 6px;
  border-radius: 4px;
  background: #e1e9f0;
  position: relative;
  margin: 14px 0;
  overflow: hidden;
}
.mark {
  position: absolute;
  height: 100%;
  background: #f6bd60;
}
summary {
  color: #425c73;
  cursor: pointer;
}
#segments {
  max-height: 210px;
  overflow: auto;
}
.segment {
  border-top: 1px solid #e1eaf2;
  margin-top: 8px;
  padding: 10px 0 2px;
}
.segment strong {
  font-size: 12px;
}
.reason,
.hint,
footer {
  color: #708194;
  font-size: 11px;
  overflow-wrap: anywhere;
}
.reason {
  margin: 6px 0 8px;
}
.hint {
  white-space: pre-line;
  margin: 10px 0;
}
footer {
  border-top: 1px solid #e1eaf2;
  padding-top: 10px;
}
[hidden] {
  display: none !important;
}
.brand-icon {
  display: block;
  flex: 0 0 36px;
  width: 36px;
  height: 36px;
}
.brand-icon svg {
  width: 100%;
  height: 100%;
}
header h1 {
  color: #243c52;
  letter-spacing: -0.4px;
}
#source {
  border-radius: 20px;
  background: #e9f4fb;
  color: #31718f;
  padding: 3px 8px;
}
#options {
  border: 0;
  color: #287d9f;
  padding: 5px 8px;
}
#video-title {
  margin: 16px 0 8px;
  color: #34506a;
}
#status {
  padding: 10px 12px;
  border-radius: 9px;
  background: #eaf4fb;
  font-size: 12px;
}
#status.error {
  background: #fff0f0;
}
.primary {
  color: white;
}
.actions {
  gap: 8px;
}
.actions button {
  flex: 1 0 auto;
}
.segment {
  padding: 12px;
  border: 1px solid #dce7ef;
  border-left: 3px solid #f6a817;
  border-radius: 10px;
  background: #fff;
}
.segment strong {
  font-size: 12px;
}
#segments {
  max-height: none;
}
.skip-switch {
  width: 100%;
  display: flex;
  align-items: center;
  margin-top: 16px;
  padding: 12px;
  border-radius: 10px;
  position: relative;
  text-align: left;
}
.skip-switch::before {
  content: "";
  position: absolute;
  right: 12px;
  width: 36px;
  height: 21px;
  border-radius: 20px;
  background: #bdc9d6;
}
.skip-switch::after {
  content: "";
  position: absolute;
  right: 29px;
  width: 15px;
  height: 15px;
  border-radius: 50%;
  background: white;
}
.skip-switch[aria-checked="true"]::before {
  background: #079ed1;
}
.skip-switch[aria-checked="true"]::after {
  right: 15px;
}

/* Native checkbox semantics, exposed as switches with keyboard and focus support. */
input[type="checkbox"][role="switch"] {
  appearance: none;
  display: inline-block;
  position: relative;
  flex: 0 0 38px;
  width: 38px;
  height: 22px;
  margin: 0;
  padding: 0;
  border: 1px solid #b8c6d4;
  border-radius: 999px;
  background: #bdc9d6;
  cursor: pointer;
  vertical-align: middle;
  transition:
    background 140ms ease,
    border-color 140ms ease;
}
input[type="checkbox"][role="switch"]::after {
  content: "";
  position: absolute;
  width: 16px;
  height: 16px;
  left: 2px;
  top: 2px;
  border-radius: 50%;
  background: #fff;
  box-shadow: 0 1px 3px #172b4d26;
  transition: transform 140ms ease;
}
input[type="checkbox"][role="switch"]:checked {
  background: #079ed1;
  border-color: #079ed1;
}
input[type="checkbox"][role="switch"]:checked::after {
  transform: translateX(16px);
}
input[type="checkbox"][role="switch"]:focus-visible {
  outline: 3px solid #079ed155;
  outline-offset: 3px;
}
input[type="checkbox"][role="switch"]:disabled {
  opacity: 0.45;
  cursor: default;
}
@media (prefers-reduced-motion: reduce) {
  input[type="checkbox"][role="switch"],
  input[type="checkbox"][role="switch"]::after {
    transition: none;
  }
}

:host {
  all: initial;
  color-scheme: light;
  font:
    13px/1.55 system-ui,
    "Microsoft YaHei",
    sans-serif;
  color: #263b51;
}
.biliskip-drawer {
  position: fixed;
  top: 16px;
  right: 16px;
  bottom: 16px;
  width: min(396px, calc(100vw - 24px));
  max-height: calc(100dvh - 32px);
  display: flex;
  flex-direction: column;
  border: 1px solid #d5e3ee;
  border-radius: 18px;
  background: #f6f9fc;
  box-shadow: 0 12px 60px #142f4a38;
  overflow: hidden;
  animation: biliskip-drawer-enter 180ms ease-out;
}
.drawer-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 10px 16px;
  background: #fff;
  border-bottom: 1px solid #e4ecf3;
}
.drawer-toolbar span {
  color: #76879a;
  font-size: 11px;
}
.drawer-scroll {
  overflow-y: auto;
  overscroll-behavior: contain;
  scrollbar-width: thin;
  flex: 1;
  min-height: 0;
}
#close-panel {
  border: 0;
  border-radius: 8px;
  background: transparent;
  font-size: 20px;
  line-height: 20px;
  padding: 5px 8px;
}
main {
  max-height: none;
  overflow: visible;
}
.project-links {
  display: flex;
  align-items: center;
  gap: 18px;
  padding: 12px 18px;
  border-top: 1px solid #e4ecf3;
  background: #fff;
}
.project-links a {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  color: #177fa6;
  text-decoration: none;
  font-size: 12px;
}
.project-links .project-link-icon,
.project-links .project-link-icon svg {
  display: block;
  flex: none;
  width: 16px;
  height: 16px;
}
.project-links a:hover {
  text-decoration: underline;
}
@keyframes biliskip-drawer-enter {
  from {
    opacity: 0;
    transform: translateX(12px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}
@media (prefers-reduced-motion: reduce) {
  .biliskip-drawer {
    animation: none;
  }
}
`,
  playerIcon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none" aria-hidden="true">
  <!-- BiliSkip monochrome player control, derived from the reviewed TV/blocked-coin composition. -->
  <g stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M10 4L15 9L20 4M13 27H6A3 3 0 0 1 3 24V12A3 3 0 0 1 6 9H24A3 3 0 0 1 27 12V15" />
    <circle cx="24" cy="24" r="6" />
    <path d="M28 20L20 28" />
  </g>
  <path d="M11 14L18 18L11 22Z" fill="currentColor" />
</svg>
`,
  homeIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#52788e" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
  <path d="m3 10 9-7 9 7M5 9v11h5v-6h4v6h5V9" />
</svg>
`,
  githubIcon: `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="#52788e" aria-hidden="true" focusable="false">
  <!--
    Source: https://github.com/primer/octicons/blob/main/icons/mark-github-16.svg
    MIT License
    Copyright (c) 2026 GitHub Inc.

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
  -->
  <path d="M6.766 11.328c-2.063-.25-3.516-1.734-3.516-3.656 0-.781.281-1.625.75-2.188-.203-.515-.172-1.609.063-2.062.625-.078 1.468.25 1.968.703.594-.187 1.219-.281 1.985-.281.765 0 1.39.094 1.953.265.484-.437 1.344-.765 1.969-.687.218.422.25 1.515.046 2.047.5.593.766 1.39.766 2.203 0 1.922-1.453 3.375-3.547 3.64.531.344.89 1.094.89 1.954v1.625c0 .468.391.734.86.547C13.781 14.359 16 11.53 16 8.03 16 3.61 12.406 0 7.984 0 3.563 0 0 3.61 0 8.031a7.88 7.88 0 0 0 5.172 7.422c.422.156.828-.125.828-.547v-1.25c-.219.094-.5.156-.75.156-1.031 0-1.64-.562-2.078-1.609-.172-.422-.36-.672-.719-.719-.187-.015-.25-.093-.25-.187 0-.188.313-.328.625-.328.453 0 .844.281 1.25.86.313.452.64.655 1.031.655s.641-.14 1-.5c.266-.265.47-.5.657-.656" />
</svg>
`,
  sectionIconmodel: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="#52788e" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
  <rect x="6" y="6" width="12" height="12" rx="3"/><path d="M9 3v3m6-3v3M9 18v3m6-3v3M3 9h3m-3 6h3m12-6h3m-3 6h3"/><path d="m10 12 1.5 1.5L15 10"/>
</svg>
`,
  sectionIconasr: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="#52788e" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
  <rect x="9" y="3" width="6" height="12" rx="3"/><path d="M6 11v1a6 6 0 0 0 12 0v-1M12 18v3m-3 0h6"/>
</svg>
`,
  sectionIconshort: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="#52788e" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
  <circle cx="12" cy="13" r="8"/><path d="M9 2h6m-3 0v3m6 1 2-2M12 9v4l3 2"/>
</svg>
`,
  sectionIconplayback: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="#52788e" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
  <path d="m7 4 13 8-13 8V4Z"/>
</svg>
`,
  sectionIconpet: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#1686aa" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M4 11V4l5 3a12 12 0 0 1 6 0l5-3v7c2 9-18 12-16 0Z"/><path d="M8 12h.01M16 12h.01M10 16l2 1 2-1"/></svg>
`,
  sectionIconshared: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="#52788e" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
  <path d="M7 18H6a4 4 0 0 1-.4-8A6.5 6.5 0 0 1 18 8a5 5 0 0 1 0 10h-1M12 12v9m-3-6 3-3 3 3"/>
</svg>
`,
  sectionIconcache: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="#52788e" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">
  <ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/>
</svg>
`,
});
